#!/bin/bash

#SBATCH --job-name=aa    # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=01:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge    # Run on either the scavenge queue

module load Anaconda3
echo "Running on $(hostname):"
#conda env create -f get_cami2_data/cami2_environment.yml
#conda activate cami2_environment

#srun snakemake --snakefile get_cami2_data/Snakefile --config DATASET=marine_short

