#!/bin/bash

#SBATCH --job-name=aa   # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=2         # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=1:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown          # Run on cn8 partition
#SBATCH --nodelist=cn8              # Request specific node cn8
#SBATCH --mail-type=BEGIN,FAIL,END

module load Anaconda3
conda env create -f get_cami2_data/cami2_environment.yml
conda activate cami2_environment

srun snakemake --snakefile get_cami2_data/Snakefile --config DATASET=marine_short

