name: cami2_environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - snakemake
  - pyyaml
  - samtools
  - strobealign
  - semibin=2.1.0
  - pip
  - pip:
      - vamb
      - Bio
