name: cami2_environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  #- snakemake
  - pyyaml
  - samtools
  - strobealign
  - pip
  - pip:
      - vamb
      - Bio
