#!/bin/bash
#SBATCH --job-name=test_ngs_pipeline  # Name of the job
#SBATCH --output=job.%j.out 
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --cpus-per-task=24             # Request 24 CPU cores
#SBATCH --time=12:00:00                # Max execution time (adjust if needed)
#SBATCH --partition=cores            

# Load modules
module load anaconda3

# Clone the repository and switch branch
git clone https://github.com/affo98/DNA-language-models-and-GLP1-microbiome-changes.git
cd DNA-language-models-and-GLP1-microbiome-changes
git switch feature/NGS_PIPELINE

echo "Downloading KneadData database..."
wget https://huttenhower.sph.harvard.edu/kneadData_databases/Homo_sapiens_hg39_T2T_Bowtie2_v0.1.tar.gz
echo "Unpacking database..."
tar -xzf Homo_sapiens_hg39_T2T_Bowtie2.tar.gz
rm Homo_sapiens_hg39_T2T_Bowtie2.tar.gz
mv bowtie2-index ngs_pipeline/src/databases/bowtie2-index/
echo "Database moved to ngs_pipeline/src/databases/bowtie2-index"

# Create and activate the Conda environment
conda env create -f environment.yaml
source activate snakemake-global  # Use 'source' for SLURM compatibility

# Run the pipeline
python run_pipeline.py -d T2D-EW_PRJEB1786 --snakemake-arg --forceall -j unlimited --cores 12
